### ISSUE TITLE
Reduce the weight of the images.

### ISSUE THREAD

**Issue by aszurita** [Taws-Espol/wids-website#36]
1. Change all images to PNG format.
2. Check the JSON files where image URLs are loaded and change their format to PNG.
Example : 
<img width="519" alt="image" src="https://github.com/Taws-Espol/wids-website/assets/127569039/70bee5f3-c204-4602-be53-f843fa5c8cc3">

Change jpeg to png

3. Reduce the weight of the images.
 You can use :
- https://www.iloveimg.com/es/comprimir-imagen/comprimir-jpg
- https://compressjpeg.com/es/

**Try to reduce the size of the images without losing quality.**

**Comment by Jonthz** [comment]
Completed
